### PR TITLE
Add codes to README.md

### PR DESCRIPTION
**Pull request by JoshWillik**
I find myself digging into the code to remember what each of the constants are called.

It would be really nice to have them on the main page.

### CODE REVIEW

**Comment by prettymuchbryce** [comment]
Great stuff Josh.

**Comment by JoshWillik** [comment]
Thanks @prettymuchbryce!

**Comment by JoshWillik** [comment]
Any chance we can get a patch version pushed to npm?

**Comment by prettymuchbryce** [comment]
Done. Thanks again.

**Pull request merged**
